@GitClub_HostAddress = https://localhost:5000

POST {{GitClub_HostAddress}}/auth/login
Accept: application/json

{
    "email": "philipp@bytefish.de",
    "rememberMe": true,
    "roles": [ "Administrator", "User" ]
}

###
