@GitClub_HostAddress = https://localhost:5000

### Login as "philipp" and pass the "Administrator" Role
POST {{GitClub_HostAddress}}/Auth/login
Content-Type: application/json

{
    "email": "philipp@bytefish.de",
    "rememberMe": true,
    "roles": [ "Administrator", "User" ]
}

### Get Organizations
GET {{GitClub_HostAddress}}/Organizations
Accept: application/json

### Get Teams
GET {{GitClub_HostAddress}}/Teams
Accept: application/json

### Get Organization Details
GET {{GitClub_HostAddress}}/Organizations/1
Accept: application/json

### Get Members for the Organization
GET {{GitClub_HostAddress}}/Organizations/1/members
Accept: application/json

### Get Members for the Organization
GET {{GitClub_HostAddress}}/Organizations/1/organization-roles/owner/users
Accept: application/json

### Get Repositories
GET {{GitClub_HostAddress}}/Repositories
Accept: application/json

### Get Issues
GET {{GitClub_HostAddress}}/Issues
Accept: application/json

### Get Collaborators for Repository 1
GET {{GitClub_HostAddress}}/Repositories/1/collaborators
Accept: application/json

### Get Teams for Repository 1
GET {{GitClub_HostAddress}}/Repositories/1/teams
Accept: application/json

### Members of Team 2 are Maintainers of Repository 1
PUT {{GitClub_HostAddress}}/Repositories/1/teams/2/Maintainer

### Create new Team "Rockstar Developers"
POST {{GitClub_HostAddress}}/Teams
Content-Type: application/json

{
    "name": "Rocrrrrrrruuuccdddddktsar Developers",
    "organizationId": 1,
    "lastEditedBy": 1
}

### Login as "charles"
POST {{GitClub_HostAddress}}/Auth/login
Content-Type: application/json

{
    "email": "charles@git.local",
    "rememberMe": true,
    "roles": [ "User" ]
}

### Create new Team as "amber"
POST {{GitClub_HostAddress}}/Teams
Content-Type: application/json

{
    "name": "My Team",
    "organizationId": 1,
    "lastEditedBy": 1
}